stages:
  prepare:
    cmd: python src/components/data_ingestion.py data/data.csv
    deps:
    - data/data.csv
    - src/components/data_ingestion.py
    params:
    - config/params.yaml:
      - data.random_state
      - data.test_size
    outs:
    - src/artifacts/processed_data.csv
    - src/artifacts/train_data.csv
    - src/artifacts/test_data.csv

  data_transform:
    cmd: python src/components/data_transformation.py
    deps:
    - src/artifacts/test_data.csv
    - src/artifacts/train_data.csv
    - src/components/data_transformation.py
    outs:
    - src/artifacts/preprocessor.pkl
  
  train:
    cmd: python src/components/model_training.py
    deps:
    - src/components/model_training.py

